"use client";

/**
 * OneSignalProvider — Initializes OneSignal Web Push SDK.
 *
 * Loads the OneSignal SDK, registers the service worker, and sets the
 * external_id to the user's Supabase auth ID for targeted push delivery.
 *
 * Setup:
 * 1. Create OneSignal app at https://dashboard.onesignal.com
 * 2. Set NEXT_PUBLIC_ONESIGNAL_APP_ID in .env
 * 3. Download the OneSignal service worker files:
 *    - public/OneSignalSDKWorker.js (auto-generated by OneSignal)
 *
 * This component should be placed inside the dashboard layout (not root)
 * so it only loads after the user is authenticated.
 */

import { useEffect, useRef } from "react";

interface OneSignalProviderProps {
  /** The authenticated user's Supabase ID */
  userId?: string | null;
}

export default function OneSignalProvider({ userId }: OneSignalProviderProps) {
  const initialized = useRef(false);

  useEffect(() => {
    const appId = process.env.NEXT_PUBLIC_ONESIGNAL_APP_ID;
    if (!appId || initialized.current) return;

    const initOneSignal = async () => {
      try {
        // Dynamically import OneSignal to avoid SSR issues
        const OneSignalModule = await import("react-onesignal");
        const OneSignal = OneSignalModule.default;

        await OneSignal.init({
          appId,
          allowLocalhostAsSecureOrigin: process.env.NODE_ENV === "development",
          notifyButton: {
            enable: false, // We handle UI ourselves
            prenotify: false,
            showCredit: false,
            text: {} as any,
          },
        });

        initialized.current = true;

        // Set external ID for targeted push
        if (userId) {
          await OneSignal.login(userId);
        }
      } catch (error) {
        console.error("[OneSignal] Init failed:", error);
      }
    };

    initOneSignal();
  }, [userId]);

  // Update external ID when user changes
  useEffect(() => {
    if (!initialized.current || !userId) return;

    const updateUser = async () => {
      try {
        const OneSignalModule = await import("react-onesignal");
        const OneSignal = OneSignalModule.default;
        await OneSignal.login(userId);
      } catch {
        // Silently ignore
      }
    };

    updateUser();
  }, [userId]);

  return null; // This is a side-effect-only component
}
