import { createHash } from "node:crypto";
import { validatePhotoFile } from "@/lib/photo/validation";
import { moderateImage } from "@/lib/content-moderation";

type ModerationStatus = "approved" | "rejected";

type ModerationSignal = {
  key: string;
  detail: string;
};

export type PhotoModerationOutcome = {
  status: ModerationStatus;
  reason: string | null;
  signals: ModerationSignal[];
  checksum: string;
};

type ImageDimensions = {
  width: number;
  height: number;
} | null;

const FLAGGED_FILENAME_PATTERN =
  /(nude|naked|porn|xxx|nsfw|explicit|sex|onlyfans|fetish)/i;

const AI_FILENAME_PATTERN =
  /(ai[-_ ]?generated|synthetic|deepfake|midjourney|stable[-_ ]?diffusion|sdxl|dall[-_ ]?e|comfyui|flux)/i;

const NON_PROFILE_FILENAME_PATTERN =
  /(screenshot|wallpaper|logo|icon|meme|banner|poster|flyer|anime|cartoon|drawing|illustration|sketch|stock|landscape)/i;

const AI_METADATA_MARKERS = [
  "midjourney",
  "stable diffusion",
  "stabilityai",
  "sdxl",
  "comfyui",
  "invokeai",
  "novelai",
  "dreamstudio",
  "dall-e",
  "generated by ai",
  "text2img",
  "img2img",
  "controlnet",
];

const HUMAN_VISUAL_LABEL_PATTERN =
  /(human|person|face|portrait|selfie|man|woman|male|female|adult|child|boy|girl|head|skin|cheek|lip|nose|eye)/i;

const NON_HUMAN_VISUAL_LABEL_PATTERN =
  /(cartoon|anime|illustration|drawing|logo|meme|poster|flyer|landscape|scenery|vehicle|car|animal|object|text|screenshot|screen|document|chart|house|building|property|architecture|interior|exterior|room|bedroom|kitchen|ai|synthetic|deepfake|cgi|render|3d)/i;

function isNegativeClassifierLabel(label: string): boolean {
  const lower = label.toLowerCase();
  return (
    lower.startsWith("no_") ||
    lower.startsWith("not_") ||
    lower.includes("_not_")
  );
}

async function evaluateHumanOnlyVisualCheck(photoUrl: string): Promise<{
  status: ModerationStatus;
  reason: string | null;
  signals: ModerationSignal[];
}> {
  const moderation = await moderateImage(photoUrl);
  const signals: ModerationSignal[] = [];
  const scoreEntries = Object.entries(moderation.scores || {});

  if (moderation.violations.length > 0 && moderation.action === "reject") {
    const lowerViolations = moderation.violations.map((item) =>
      item.toLowerCase()
    );
    const hasIdentityViolation = lowerViolations.some((item) =>
      item.includes("ai_or_synthetic") ||
      item.includes("unrelated_or_non_human") ||
      item.includes("human_subject_not_detected")
    );

    return {
      status: "rejected",
      reason:
        hasIdentityViolation
          ? "Only photos of real human beings are allowed. Please upload a clear photo of yourself."
          : "This image violates photo safety rules. Please upload a clear, real photo of yourself.",
      signals: [
        {
          key: "visual_policy",
          detail: moderation.violations.join(", "),
        },
      ],
    };
  }

  if (scoreEntries.length === 0) {
    return {
      status: "rejected",
      reason:
        "We could not verify a clear human subject automatically. Please upload a clearer photo of yourself.",
      signals: [
        {
          key: "visual_classifier_unavailable",
          detail:
            "No classifier scores returned, so the image could not be verified as a real human photo.",
        },
      ],
    };
  }

  const explicitAiScore =
    typeof moderation.scores.ai_or_synthetic === "number"
      ? moderation.scores.ai_or_synthetic
      : null;
  if (explicitAiScore !== null && explicitAiScore >= 0.7) {
    return {
      status: "rejected",
      reason:
        "AI-generated or synthetic images are not allowed. Please upload a real photo of yourself.",
      signals: [
        {
          key: "ai_or_synthetic",
          detail: explicitAiScore.toFixed(2),
        },
      ],
    };
  }

  const explicitNonHumanScore =
    typeof moderation.scores.unrelated_or_non_human === "number"
      ? moderation.scores.unrelated_or_non_human
      : null;
  const explicitHumanScore =
    typeof moderation.scores.human_photo === "number"
      ? moderation.scores.human_photo
      : null;
  const strongIdentityHumanEvidence =
    explicitHumanScore !== null &&
    explicitHumanScore >= 0.55 &&
    (explicitNonHumanScore === null ||
      explicitHumanScore >= explicitNonHumanScore + 0.2);

  if (explicitNonHumanScore !== null && explicitNonHumanScore >= 0.72) {
    return {
      status: "rejected",
      reason:
        "Only photos of real human beings are allowed. Please upload a clear photo of yourself.",
      signals: [
        {
          key: "unrelated_or_non_human",
          detail: explicitNonHumanScore.toFixed(2),
        },
      ],
    };
  }

  const nonHumanHits = scoreEntries.filter(
    ([label, score]) =>
      !isNegativeClassifierLabel(label) &&
      NON_HUMAN_VISUAL_LABEL_PATTERN.test(label) &&
      score >= 0.72
  );

  if (nonHumanHits.length > 0 && !strongIdentityHumanEvidence) {
    const strongest = nonHumanHits.sort((a, b) => b[1] - a[1])[0];
    return {
      status: "rejected",
      reason:
        "Only photos of real human beings are allowed. Please upload a clear photo of yourself.",
      signals: [
        {
          key: "non_human_visual_label",
          detail: `${strongest[0]}:${strongest[1].toFixed(2)}`,
        },
      ],
    };
  }

  const humanHits = scoreEntries.filter(
    ([label, score]) =>
      !isNegativeClassifierLabel(label) &&
      HUMAN_VISUAL_LABEL_PATTERN.test(label) &&
      score >= 0.18
  );
  const weakHumanHits = scoreEntries.filter(
    ([label, score]) =>
      !isNegativeClassifierLabel(label) &&
      HUMAN_VISUAL_LABEL_PATTERN.test(label) &&
      score >= 0.1
  );

  if (
    explicitHumanScore !== null &&
    explicitHumanScore >= 0.38 &&
    (explicitNonHumanScore === null ||
      explicitHumanScore >= explicitNonHumanScore + 0.08)
  ) {
    signals.push({
      key: "human_subject_detected",
      detail: `human_photo:${explicitHumanScore.toFixed(2)}`,
    });
    if (nonHumanHits.length > 0) {
      const strongest = nonHumanHits.sort((a, b) => b[1] - a[1])[0];
      signals.push({
        key: "generic_non_human_labels_overridden",
        detail: `${strongest[0]}:${strongest[1].toFixed(2)}`,
      });
    }
    return { status: "approved", reason: null, signals };
  }

  if (humanHits.length === 0) {
    const nonHumanLooksWeak =
      explicitNonHumanScore === null || explicitNonHumanScore < 0.55;
    const aiLooksWeak = explicitAiScore === null || explicitAiScore < 0.55;
    const hasWeakHumanEvidence =
      (explicitHumanScore !== null && explicitHumanScore >= 0.12) ||
      weakHumanHits.length > 0;

    if (nonHumanLooksWeak && aiLooksWeak && hasWeakHumanEvidence) {
      signals.push({
        key: "human_subject_ambiguous",
        detail:
          "No strong human hit was returned, but weak human evidence exists and AI/non-human confidence remained low.",
      });
      return { status: "approved", reason: null, signals };
    }

    return {
      status: "rejected",
      reason:
        "We could not verify a clear human subject automatically. Please upload a clearer photo of yourself.",
      signals: [
        {
          key: "human_subject_missing",
          detail:
            "No strong human/person/face indicators from visual classifier.",
        },
      ],
    };
  }

  const strongestHuman = humanHits.sort((a, b) => b[1] - a[1])[0];
  signals.push({
    key: "human_subject_detected",
    detail: `${strongestHuman[0]}:${strongestHuman[1].toFixed(2)}`,
  });

  return { status: "approved", reason: null, signals };
}

export async function evaluateRemotePhotoUrlModeration(
  photoUrl: string
): Promise<PhotoModerationOutcome> {
  const visualCheck = await evaluateHumanOnlyVisualCheck(photoUrl);
  return {
    status: visualCheck.status,
    reason: visualCheck.reason,
    signals: visualCheck.signals,
    checksum: "",
  };
}

function detectPngAlphaChannel(bytes: Buffer): boolean | null {
  const pngSignature =
    bytes.length >= 26 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47;

  if (!pngSignature) return null;

  const colorType = bytes[25];
  return colorType === 4 || colorType === 6;
}

function detectAiMetadataMarker(bytes: Buffer): string | null {
  const metadataText = bytes.toString("latin1").toLowerCase();
  return (
    AI_METADATA_MARKERS.find((marker) => metadataText.includes(marker)) || null
  );
}

function detectPngDimensions(bytes: Buffer): ImageDimensions {
  const pngSignature =
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47;

  if (!pngSignature || bytes.length < 24) {
    return null;
  }

  return {
    width: bytes.readUInt32BE(16),
    height: bytes.readUInt32BE(20),
  };
}

function detectJpegDimensions(bytes: Buffer): ImageDimensions {
  if (bytes.length < 4 || bytes[0] !== 0xff || bytes[1] !== 0xd8) {
    return null;
  }

  let offset = 2;
  while (offset < bytes.length - 1) {
    if (bytes[offset] !== 0xff) {
      offset += 1;
      continue;
    }

    const marker = bytes[offset + 1];

    if (marker === 0xd9 || marker === 0xda) {
      break;
    }

    if (offset + 4 > bytes.length) {
      break;
    }

    const segmentLength = bytes.readUInt16BE(offset + 2);
    if (segmentLength < 2) {
      break;
    }

    const isStartOfFrame =
      marker >= 0xc0 &&
      marker <= 0xcf &&
      ![0xc4, 0xc8, 0xcc].includes(marker);

    if (isStartOfFrame && offset + 9 <= bytes.length) {
      return {
        height: bytes.readUInt16BE(offset + 5),
        width: bytes.readUInt16BE(offset + 7),
      };
    }

    offset += segmentLength + 2;
  }

  return null;
}

function detectWebpDimensions(bytes: Buffer): ImageDimensions {
  const hasRiff = bytes.length >= 16 && bytes.toString("ascii", 0, 4) === "RIFF";
  const hasWebp = bytes.length >= 16 && bytes.toString("ascii", 8, 12) === "WEBP";

  if (!hasRiff || !hasWebp) {
    return null;
  }

  const chunkType = bytes.toString("ascii", 12, 16);

  if (chunkType === "VP8X" && bytes.length >= 30) {
    const widthMinusOne = bytes.readUIntLE(24, 3);
    const heightMinusOne = bytes.readUIntLE(27, 3);
    return {
      width: widthMinusOne + 1,
      height: heightMinusOne + 1,
    };
  }

  return null;
}

function detectImageDimensions(bytes: Buffer): ImageDimensions {
  return (
    detectPngDimensions(bytes) ||
    detectJpegDimensions(bytes) ||
    detectWebpDimensions(bytes)
  );
}

export async function evaluateAutomatedPhotoModeration(
  file: File,
  options?: {
    publicUrl?: string;
  }
): Promise<PhotoModerationOutcome> {
  const validation = validatePhotoFile(file);
  const signals: ModerationSignal[] = [];

  if (!validation.valid) {
    return {
      status: "rejected",
      reason: validation.errors[0] || "Invalid image file.",
      signals,
      checksum: "",
    };
  }

  if (FLAGGED_FILENAME_PATTERN.test(file.name)) {
    return {
      status: "rejected",
      reason: "Photo filename triggered content safety checks.",
      signals: [
        {
          key: "filename_policy",
          detail: "Sensitive keyword found in filename.",
        },
      ],
      checksum: "",
    };
  }

  if (AI_FILENAME_PATTERN.test(file.name)) {
    return {
      status: "rejected",
      reason:
        "AI-generated or synthetic images are not allowed. Please upload a real photo of yourself.",
      signals: [
        {
          key: "ai_filename_policy",
          detail: "Filename matches AI/synthetic keywords.",
        },
      ],
      checksum: "",
    };
  }

  if (NON_PROFILE_FILENAME_PATTERN.test(file.name)) {
    return {
      status: "rejected",
      reason:
        "Please upload a real profile photo of yourself (no screenshots, logos, or illustrations).",
      signals: [
        {
          key: "non_profile_filename_policy",
          detail: "Filename matches non-profile keywords.",
        },
      ],
      checksum: "",
    };
  }

  const bytes = Buffer.from(await file.arrayBuffer());
  const checksum = createHash("sha256").update(bytes).digest("hex");

  const aiMarker = detectAiMetadataMarker(bytes);
  if (aiMarker) {
    return {
      status: "rejected",
      reason:
        "This image appears to be AI-generated. Please upload a real photo of yourself.",
      signals: [
        {
          key: "ai_metadata",
          detail: `Detected marker: ${aiMarker}`,
        },
      ],
      checksum,
    };
  }

  if (file.size < 20 * 1024) {
    return {
      status: "rejected",
      reason: "Image quality too low. Please upload a clearer photo.",
      signals: [
        {
          key: "file_size",
          detail: "File below minimum quality threshold (20KB).",
        },
      ],
      checksum,
    };
  }

  const dimensions = detectImageDimensions(bytes);
  if (dimensions) {
    const aspectRatio = dimensions.width / Math.max(dimensions.height, 1);
    const hasPngAlpha = detectPngAlphaChannel(bytes);

    if (dimensions.width < 320 || dimensions.height < 320) {
      return {
        status: "rejected",
        reason: "Image resolution is too low. Minimum is 320x320.",
        signals: [
          {
            key: "resolution",
            detail: `${dimensions.width}x${dimensions.height}`,
          },
        ],
        checksum,
      };
    }

    if (hasPngAlpha) {
      return {
        status: "rejected",
        reason:
          "Transparent images are not allowed. Please upload a real camera photo.",
        signals: [
          {
            key: "transparency",
            detail: "PNG contains alpha channel.",
          },
        ],
        checksum,
      };
    }

    if (aspectRatio < 0.45 || aspectRatio > 2.2) {
      return {
        status: "rejected",
        reason: "Image aspect ratio is not supported.",
        signals: [
          {
            key: "aspect_ratio",
            detail: aspectRatio.toFixed(2),
          },
        ],
        checksum,
      };
    }

    signals.push(
      {
        key: "resolution",
        detail: `${dimensions.width}x${dimensions.height}`,
      },
      {
        key: "aspect_ratio",
        detail: aspectRatio.toFixed(2),
      }
    );
  } else {
    signals.push({
      key: "dimension_parser",
      detail: "Could not parse image dimensions automatically.",
    });
  }

  if (options?.publicUrl) {
    const visualCheck = await evaluateHumanOnlyVisualCheck(options.publicUrl);
    if (visualCheck.status !== "approved") {
      return {
        status: visualCheck.status,
        reason:
          visualCheck.reason ||
          "Only photos of real human beings are allowed.",
        signals: [...signals, ...visualCheck.signals],
        checksum,
      };
    }
    signals.push(...visualCheck.signals);
  }

  return {
    status: "approved",
    reason: null,
    signals,
    checksum,
  };
}
